# Generated by Django 5.1.5 on 2025-02-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_formpagelanding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormPageLanding',
        ),
    ]
