# Generated by Django 5.1.5 on 2025-01-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdetailpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_publish_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='blog_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Blog Title'),
        ),
    ]
