# Generated by Django 5.1.5 on 2025-01-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menusnippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusnippets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
