# Generated by Django 5.1.5 on 2025-01-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_menusnippets_id'),
        ('home', '0004_carrierspage_privacypolicypage_and_more'),
    ]

    operations = [
    ]
