# Generated by Django 5.1.5 on 2025-02-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20250128_1106'),
        ('home', '0005_merge_20250202_0517'),
    ]

    operations = [
    ]
